ports:
  - port: 5000
    onOpen: open-preview

tasks:
  - name: Start Redis tack
    init: |
     docker-compose pull
    command: |
     alias redis-cli="docker exec -it redis redis-cli" 
     echo "Use redis-cli to interact with Redis here."
     docker-compose up -d
     gp sync-done finished
    openMode: split-left
  - name: Start Express Application
    init: |
      npm install
    command: |
      gp sync-await finished && \
      npm run dev
    openMode: split-right
